# Generated by Django 2.2.9 on 2020-02-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200215_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
