# Generated by Django 2.2.9 on 2020-02-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200229_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.FileField(blank=True, default=None, null=True, upload_to='post_Image'),
        ),
    ]
