# Generated by Django 2.2.9 on 2020-02-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200229_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
