# Generated by Django 2.2.9 on 2020-03-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200229_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
