# Generated by Django 2.2.9 on 2020-03-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_item_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.FileField(blank=True, default=None, null=True, upload_to='post_Image'),
        ),
    ]
