# Generated by Django 2.2.9 on 2020-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200310_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.FileField(blank=True, default=None, null=True, upload_to='frontend/src/assets'),
        ),
    ]
